// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace TH.ClientLayer.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190704152903_DatabaseSetup")]
    partial class DatabaseSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("TH.ClientLayer.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("Power")
                        .HasColumnName("power")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
